/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;

import java.awt.Color;
import java.awt.Dimension;
import java.sql.*;
import javax.swing.*;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author dev
 */
public class Main extends javax.swing.JFrame {

    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
   
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Room = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        Discharge = new javax.swing.JLabel();
        Admit3 = new javax.swing.JLabel();
        Admit4 = new javax.swing.JLabel();
        Admit6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Admit = new javax.swing.JLabel();
        Admit1 = new javax.swing.JLabel();
        Admit2 = new javax.swing.JLabel();
        Admit5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        Wards = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        Admit7 = new javax.swing.JLabel();
        Admit8 = new javax.swing.JLabel();
        Admit9 = new javax.swing.JLabel();
        Discharge1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        Patient = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(10, 24, 39), 1, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(26, 128, 215));

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setFont(new java.awt.Font("Playfair Display Black", 0, 24)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Dashboard");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addContainerGap(770, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 944, -1));

        jPanel4.setBackground(new java.awt.Color(10, 24, 39));

        jPanel5.setBackground(new java.awt.Color(33, 33, 33));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(52, 73, 94));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
        });

        Room.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        Room.setForeground(java.awt.Color.white);
        Room.setText("Rooms");
        Room.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RoomMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RoomMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RoomMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Room, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(Room, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(52, 73, 94));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
        });

        Discharge.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        Discharge.setForeground(java.awt.Color.white);
        Discharge.setText("Discharge");
        Discharge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DischargeMouseClicked(evt);
            }
        });

        Admit3.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        Admit3.setForeground(java.awt.Color.white);
        Admit3.setText("Room");
        Admit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Admit3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Admit3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Admit3MouseEntered(evt);
            }
        });

        Admit4.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        Admit4.setForeground(java.awt.Color.white);
        Admit4.setText("Ward");
        Admit4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Admit4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Admit4MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Admit4MouseEntered(evt);
            }
        });

        Admit6.setFont(new java.awt.Font("Raleway Black", 0, 24)); // NOI18N
        Admit6.setForeground(java.awt.Color.white);
        Admit6.setText("<");
        Admit6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Admit6MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Admit6MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Admit6MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Admit6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Admit4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Admit3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(Discharge, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Discharge, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Admit6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Admit3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Admit4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/logout.png"))); // NOI18N
        jLabel1.setToolTipText("Logout");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(52, 73, 94));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel10MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel10MouseEntered(evt);
            }
        });

        Admit.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        Admit.setForeground(java.awt.Color.white);
        Admit.setText("Room");
        Admit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdmitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdmitMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdmitMouseEntered(evt);
            }
        });

        Admit1.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        Admit1.setForeground(java.awt.Color.white);
        Admit1.setText("Admit");
        Admit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Admit1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Admit1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Admit1MouseEntered(evt);
            }
        });

        Admit2.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        Admit2.setForeground(java.awt.Color.white);
        Admit2.setText("Ward");
        Admit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Admit2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Admit2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Admit2MouseEntered(evt);
            }
        });

        Admit5.setFont(new java.awt.Font("Raleway Black", 0, 24)); // NOI18N
        Admit5.setForeground(java.awt.Color.white);
        Admit5.setText("<");
        Admit5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Admit5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Admit5MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Admit5MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Admit5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Admit2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Admit, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(Admit1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admit5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Admit1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(Admit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Admit2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(52, 73, 94));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel11MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel11MouseEntered(evt);
            }
        });

        Wards.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        Wards.setForeground(java.awt.Color.white);
        Wards.setText("Wards");
        Wards.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WardsMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                WardsMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                WardsMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Wards, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(Wards, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(52, 73, 94));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel14MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel14MouseEntered(evt);
            }
        });

        Admit7.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        Admit7.setForeground(java.awt.Color.white);
        Admit7.setText("Room");
        Admit7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Admit7MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Admit7MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Admit7MouseEntered(evt);
            }
        });

        Admit8.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        Admit8.setForeground(java.awt.Color.white);
        Admit8.setText("Ward");
        Admit8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Admit8MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Admit8MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Admit8MouseEntered(evt);
            }
        });

        Admit9.setFont(new java.awt.Font("Raleway Black", 0, 24)); // NOI18N
        Admit9.setForeground(java.awt.Color.white);
        Admit9.setText("<");
        Admit9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Admit9MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Admit9MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Admit9MouseEntered(evt);
            }
        });

        Discharge1.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        Discharge1.setForeground(java.awt.Color.white);
        Discharge1.setText("Bills");
        Discharge1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Discharge1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Admit9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Admit8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Admit7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Discharge1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admit9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Discharge1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Admit7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Admit8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 230, 580));

        jPanel1.setBackground(new java.awt.Color(52, 70, 93));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(10, 24, 39), 1, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(130, 130));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/doctor(1).png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 150, 150));

        jPanel8.setBackground(new java.awt.Color(52, 70, 93));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(10, 24, 39), 1, true));
        jPanel8.setPreferredSize(new java.awt.Dimension(130, 130));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel8MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel8MouseEntered(evt);
            }
        });

        Patient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/patient.png"))); // NOI18N
        Patient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PatientMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PatientMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Patient)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Patient)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 150, 150));

        jPanel9.setBackground(new java.awt.Color(52, 70, 93));
        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(10, 24, 39), 1, true));
        jPanel9.setPreferredSize(new java.awt.Dimension(130, 130));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel9MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel9MouseEntered(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/nurse.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, 150, 150));

        jPanel22.setBackground(new java.awt.Color(52, 70, 93));
        jPanel22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(10, 24, 39), 1, true));

        jLabel12.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/IPD.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        jPanel3.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 150, 150));

        jPanel23.setBackground(new java.awt.Color(52, 70, 93));
        jPanel23.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(10, 24, 39), 1, true));

        jLabel6.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/OPD.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 150, 150));

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("   Nurse/Wardboy");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 170, -1));

        jLabel4.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("        Doctors");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 140, -1));

        jLabel5.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("        Patients");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 140, -1));

        jLabel7.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("  Manage Password");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 180, -1));

        jLabel11.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("          About");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 170, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientMouseClicked
        this.dispose();
        Patient p=new Patient();
        p.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_PatientMouseClicked

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        jPanel6.setBackground(new Color(52,73,94));        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseExited

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        jPanel6.setBackground(new Color(30,34,61));
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
     
    }//GEN-LAST:event_jPanel7MouseEntered

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
   
    }//GEN-LAST:event_jPanel7MouseExited

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
     jPanel1.setBackground(new Color(10,24,39));
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        jPanel1.setBackground(new Color(52,70,93));
    }//GEN-LAST:event_jPanel1MouseExited

    private void RoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomMouseClicked
     this.dispose();
     Room frm=new Room();
     frm.setVisible(true);
    }//GEN-LAST:event_RoomMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        this.dispose();
        Nurse_Wardboy frm=new Nurse_Wardboy();
        frm.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void RoomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomMouseEntered
     jPanel6.setBackground(new Color(30,34,61));        // TODO add your handling code here:
    }//GEN-LAST:event_RoomMouseEntered

    private void RoomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomMouseExited
        jPanel6.setBackground(new Color(52,73,94));         // TODO add your handling code here:
    }//GEN-LAST:event_RoomMouseExited

    private void jPanel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseEntered
        jPanel8.setBackground(new Color(10,24,39)); // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseEntered

    private void jPanel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseExited
         jPanel8.setBackground(new Color(52,70,93));// TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseExited

    private void PatientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientMouseEntered
         jPanel8.setBackground(new Color(10,24,39)); // TODO add your handling code here:
    }//GEN-LAST:event_PatientMouseEntered

    private void PatientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientMouseExited
        jPanel8.setBackground(new Color(52,70,93));//  TODO add your handling code here:
    }//GEN-LAST:event_PatientMouseExited

    private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseEntered
         jPanel9.setBackground(new Color(10,24,39));// TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MouseEntered

    private void jPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseExited
        jPanel9.setBackground(new Color(52,70,93)); // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MouseExited

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
         jPanel9.setBackground(new Color(10,24,39));// TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        jPanel9.setBackground(new Color(52,70,93)); 
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        jPanel1.setBackground(new Color(10,24,39));  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        jPanel1.setBackground(new Color(52,70,93)); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.dispose();
        Doctor d=new Doctor();
        d.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
        Login l=new Login();
        l.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void AdmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdmitMouseClicked
       this.dispose();
       Patient_Admit_Room frm=new Patient_Admit_Room();
       frm.setVisible(true);
    }//GEN-LAST:event_AdmitMouseClicked

    private void AdmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdmitMouseExited
      jPanel10.setBackground(new Color(52,70,93));  // TODO add your handling code here:
    }//GEN-LAST:event_AdmitMouseExited

    private void AdmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdmitMouseEntered
    
    }//GEN-LAST:event_AdmitMouseEntered

    private void jPanel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseExited
     jPanel10.setBackground(new Color(52,70,93)); 
    }//GEN-LAST:event_jPanel10MouseExited

    private void jPanel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseEntered
           
    }//GEN-LAST:event_jPanel10MouseEntered

    private void WardsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WardsMouseClicked
    this.dispose();
    Wards frm=new Wards();
    frm.setVisible(true);
    }//GEN-LAST:event_WardsMouseClicked

    private void WardsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WardsMouseExited
    jPanel11.setBackground(new Color(52,73,94));  // TODO add your handling code here:
    }//GEN-LAST:event_WardsMouseExited

    private void WardsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WardsMouseEntered
    jPanel11.setBackground(new Color(30,34,61)); // TODO add your handling code here:
    }//GEN-LAST:event_WardsMouseEntered

    private void jPanel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseExited
     jPanel11.setBackground(new Color(52,73,94));      // TODO add your handling code here:
    }//GEN-LAST:event_jPanel11MouseExited

    private void jPanel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseEntered
     jPanel11.setBackground(new Color(30,34,61));
    }//GEN-LAST:event_jPanel11MouseEntered

    private void DischargeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DischargeMouseClicked
    jPanel7.setSize(240,132);
     jPanel14.setLocation(0,312);
     jPanel6.setLocation(0,358);
     jPanel11.setLocation(0,404);
    
    }//GEN-LAST:event_DischargeMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        this.dispose();
        About frm=new About();
        frm.setVisible(true);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void Admit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit1MouseClicked
       jPanel10.setSize(240,144);
       jPanel7.setLocation(0,278);
       jPanel14.setLocation(0,324);
       jPanel6.setLocation(0,370);
       jPanel11.setLocation(0,416);
       
    }//GEN-LAST:event_Admit1MouseClicked

    private void Admit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit1MouseExited
         
    }//GEN-LAST:event_Admit1MouseExited

    private void Admit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit1MouseEntered
        
    }//GEN-LAST:event_Admit1MouseEntered

    private void Admit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit2MouseClicked
     this.dispose();
     Patient_Admit_Ward frm=new Patient_Admit_Ward();
     frm.setVisible(true);
    }//GEN-LAST:event_Admit2MouseClicked

    private void Admit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit2MouseExited

    private void Admit2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit2MouseEntered

    private void Admit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit3MouseClicked
      this.hide();
      Patient_Discharge_Room frm=new Patient_Discharge_Room();
      frm.setVisible(true);
    }//GEN-LAST:event_Admit3MouseClicked

    private void Admit3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit3MouseExited

    private void Admit3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit3MouseEntered

    private void Admit4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit4MouseClicked
        this.hide();
        Patient_Discharge_Ward frm=new Patient_Discharge_Ward();
        frm.setVisible(true);
    }//GEN-LAST:event_Admit4MouseClicked

    private void Admit4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit4MouseExited

    private void Admit4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit4MouseEntered

    private void Admit5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit5MouseClicked
        jPanel10.setSize(240,40);
        jPanel7.setLocation(0,174);
        jPanel14.setLocation(0,220);
       jPanel6.setLocation(0,266);
       jPanel11.setLocation(0,312);
   
    }//GEN-LAST:event_Admit5MouseClicked

    private void Admit5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit5MouseExited

    private void Admit5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit5MouseEntered

    private void Admit6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit6MouseClicked
        jPanel7.setSize(234,40);
        jPanel14.setLocation(0,220);
       jPanel6.setLocation(0,266);
       jPanel11.setLocation(0,312);
      
    }//GEN-LAST:event_Admit6MouseClicked

    private void Admit6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit6MouseExited

    private void Admit6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit6MouseEntered

    private void Discharge1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Discharge1MouseClicked
       jPanel14.setSize(240,134);        
        jPanel6.setLocation(0,360);
       jPanel11.setLocation(0,406);
     
    }//GEN-LAST:event_Discharge1MouseClicked

    private void Admit7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit7MouseClicked
        this.hide();
        Bill_Room frm=new Bill_Room();
        frm.setVisible(true);
    }//GEN-LAST:event_Admit7MouseClicked

    private void Admit7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit7MouseExited

    private void Admit7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit7MouseEntered

    private void Admit8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit8MouseClicked
        this.hide();
        Bill_Ward frm=new Bill_Ward();
        frm.setVisible(true);
    }//GEN-LAST:event_Admit8MouseClicked

    private void Admit8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit8MouseExited

    private void Admit8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit8MouseEntered

    private void Admit9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit9MouseClicked
       jPanel14.setSize(234, 40);
       jPanel6.setLocation(0,266);
       jPanel11.setLocation(0,312);
      
    }//GEN-LAST:event_Admit9MouseClicked

    private void Admit9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit9MouseExited

    private void Admit9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit9MouseEntered

    private void jPanel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel14MouseExited

    private void jPanel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel14MouseEntered

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       this.dispose();
       Reset_Password frm= new Reset_Password();
       frm.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admit;
    private javax.swing.JLabel Admit1;
    private javax.swing.JLabel Admit2;
    private javax.swing.JLabel Admit3;
    private javax.swing.JLabel Admit4;
    private javax.swing.JLabel Admit5;
    private javax.swing.JLabel Admit6;
    private javax.swing.JLabel Admit7;
    private javax.swing.JLabel Admit8;
    private javax.swing.JLabel Admit9;
    private javax.swing.JLabel Discharge;
    private javax.swing.JLabel Discharge1;
    private javax.swing.JLabel Patient;
    private javax.swing.JLabel Room;
    private javax.swing.JLabel Wards;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
